name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - DEV # Include other branches if necessary
  pull_request:
    branches:
      - master
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_PATH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY_PATH }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
          DRAGONFLY_REPO: ${{ secrets.DRAGONFLY_REPO }}
          DRAGONFLY_PORT: ${{ secrets.DRAGONFLY_PORT }}
          DRAGONFLY_SECRET: ${{ secrets.DRAGONFLY_SECRET }}
          FIREFLY_REPO: ${{ secrets.FIREFLY_REPO }}
          FIREFLY_PORT: ${{ secrets.FIREFLY_PORT }}
          FIREFLY_SECRET: ${{ secrets.FIREFLY_SECRET }}
        run: |
          # Here you can add commands to SSH into your Droplet and run Docker commands
          ssh root@${{ secrets.DROPLET_IP }} << 'EOF'
          # Pull the latest code from the repository
          git clone $DRAGONFLY_REPO /var/www/dragonfly || (cd /var/www/dragonfly && git pull)

          # Install dependencies and start the application
          cd /var/www/dragonfly
          npm install
          pm2 start --name "dragonfly" npm -- start

          # Repeat for Firefly if needed
          git clone $FIREFLY_REPO /var/www/firefly || (cd /var/www/firefly && git pull)
          cd /var/www/firefly
          npm install
          pm2 start --name "firefly" npm -- start
          EOF
