name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Adjust as necessary for your default branch
  pull_request:
    branches:
      - main  # Adjust as necessary for your default branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8  # Use the latest version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          # Set environment variables for the initialization script
          echo "Running the initialization script..."
          SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
          NODE_VERSION="${{ secrets.NODE_VERSION }}"
          AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}"
          AWS_SECRET_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION="${{ secrets.AWS_REGION }}"
          
          # Execute the initial setup script with environment variables
          bash /tmp/initial_setup.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          NODE_VERSION: ${{ secrets.NODE_VERSION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
