name: Terraform DigitalOcean Apply/Destroy Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Adjust version if needed

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
        aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
        aws configure set default.region ap-south-1  

    - name: Set DigitalOcean Token
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      run: |
        echo "machine api.digitalocean.com login ${DIGITALOCEAN_TOKEN}" > ~/.netrc
        chmod 600 ~/.netrc  # Ensure permissions are correct

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan (Apply)
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform plan 

    - name: Approve and Apply Plan
      if: ${{ github.event.inputs.action == 'apply' }}
      run: |
        echo "Applying Terraform plan with auto-approve... "
        terraform apply --auto-approve -

    - name: Terraform Plan (Destroy)
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform plan -destroy 

    - name: Approve and Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: |
        echo "Destroying Terraform resources with auto-approve... "
        terraform destroy --auto-approve tfplan
