name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Debug Environment Variables
        run: env

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_node_version: ${{ secrets.NODE_VERSION }}
          TF_VAR_ssh_private_key_path: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          TF_VAR_ssh_public_key_path: ${{ secrets.SSH_PUBLIC_KEY_PATH }}
          TF_VAR_dragonfly_repo: ${{ secrets.DRAGONFLY_REPO }}
          TF_VAR_firefly_repo: ${{ secrets.FIREFLY_REPO }}
          TF_VAR_firefly_port: ${{ secrets.FIREFLY_PORT }}
          TF_VAR_dragonfly_port: ${{ secrets.DRAGONFLY_PORT }}
          TF_VAR_firefly_domain: ${{ secrets.FIREFLY_DOMAIN }}
          TF_VAR_dragonfly_domain: ${{ secrets.DRAGONFLY_DOMAIN }}
          TF_VAR_dragonfly_secret: ${{ secrets.DRAGONFLY_SECRET }}
          TF_VAR_firefly_secret: ${{ secrets.FIREFLY_SECRET }}
          TF_VAR_dragonfly_branch: ${{ secrets.DRAGONFLY_BRANCH }}
          TF_VAR_firefly_branch: ${{ secrets.FIREFLY_BRANCH }}
          TF_VAR_app_action: ${{ secrets.APP_ACTION }}
