name: Terraform CI/CD

on:
  push:
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version:1.9.8

    - name: Configure AWS Credentials
      run: |
        echo "[default]" > $HOME/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> $HOME/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> $HOME/.aws/credentials

    - name: Set up SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_PATH }}" > ~/.ssh/sumit
        chmod 600 ~/.ssh/sumit
        echo "${{ secrets.SSH_PUBLIC_KEY_PATH }}" > ~/.ssh/sumit.pub
        chmod 644 ~/.ssh/sumit.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=terraform.tfvars
      env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
