name: Terraform DigitalOcean Deployment

on:
  push:
    branches:
      - main  # Adjust to your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7  # Adjust version as needed

      - name: Configure DigitalOcean Token
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}  # Store your DigitalOcean token in GitHub secrets
        run: |
          echo "machine api.digitalocean.com login ${DIGITALOCEAN_TOKEN}" > ~/.netrc
          chmod 600 ~/.netrc  # Ensure permissions are correct

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
