name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version here

      - name: Install Dependencies
        run: |
          npm install

      - name: Configure AWS CLI
        run: |
          echo "Setting up AWS CLI..."
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_KEY }}"
          aws configure set region "ap-south-1"

      - name: Run Terraform Plan
        run: |
          terraform init
          terraform plan

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve

      - name: Deploy Application
        run: |
          # Your deployment commands go here
