name: CI/CD Pipeline for Application Setup

on:
  push:
    branches:
      - main
      - DEV  # Runs on push to both 'main' and 'dev'
  workflow_dispatch:  # Optional manual trigger

env:
  NVM_DIR: "$HOME/.nvm"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Apply/Destroy based on the branch
      - name: Terraform Apply
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            terraform apply -auto-approve -var="app_action=setup_dragonfly"
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            terraform apply -auto-approve -var="app_action=setup_firefly"
          fi

      # Step 5: Execute the Application Setup Script
      - name: Run Setup Script
        run: |
          chmod +x ./setup.sh  # Ensure script is executable
          if [ "${{ github.ref_name }}" == "main" ]; then
            ./setup.sh setup_dragonfly
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            ./setup.sh setup_firefly
          fi

      # Optional Step 6: Run Destroy on Workflow Dispatch (manual trigger)
      - name: Run Destroy Script (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          ./setup.sh destroy_dragonfly || ./setup.sh destroy_firefly
