name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on push to both 'main' and 'dev'
  workflow_dispatch:  # Enables manual trigger
    inputs:
      action:  # Input to choose between apply or destroy
        description: "Select the Terraform action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download terraform.tfvars from S3
        run: |
          aws s3 cp s3://sumit-cli/terraform.tfvars ./terraform.tfvars || { 
            echo "Failed to download terraform.tfvars"; 
            exit 1; 
          }

      - name: Terraform Init
        run: |
          terraform init || { echo "Terraform init failed"; exit 1; }

      - name: Terraform ${ { github.event.inputs.action } }  # Dynamically choose apply or destroy
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -var="app_action=setup_dragonfly" -var="ssh_public_key=${SSH_PUBLIC_KEY}" -var="ssh_private_key=${SSH_PRIVATE_KEY}" || { 
              echo "Terraform apply failed"; 
              exit 1; 
            }
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform apply -var="app_action=destroy_dragonfly" -var="ssh_public_key=${SSH_PUBLIC_KEY}" -var="ssh_private_key=${SSH_PRIVATE_KEY}" || { 
              echo "Terraform destroy failed"; 
              exit 1; 
            }
          fi