name: Run Terraform Action

on:
  workflow_run:
    workflows: ["Terraform Deploy"]  # Triggered after Terraform Deploy workflow completes
    types:
      - completed

jobs:
  run-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Initial Setup Script on Droplet
        run: |
          echo "Running initial setup script on Droplet..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@${{ secrets.DROPLET_IP }} \
            'bash /tmp/1.sh'

      - name: Run Terraform Action
        run: |
          echo "Running action: apply"

          case "apply" in
            apply)
              echo "Running terraform apply..."
              terraform apply -auto-approve \
                -var="ssh_public_key=${SSH_PUBLIC_KEY}" \
                -var="ssh_private_key=${SSH_PRIVATE_KEY}" \
                -var="droplet_ip=${DROPLET_IP}" || {
                  echo "Terraform apply failed";
                  exit 1;
                }
              ;;
            destroy)
              echo "Running terraform destroy..."
              terraform destroy -auto-approve \
                -var="ssh_public_key=${SSH_PUBLIC_KEY}" \
                -var="ssh_private_key=${SSH_PRIVATE_KEY}" \
                -var="droplet_ip=${DROPLET_IP}" || {
                  echo "Terraform destroy failed";
                  exit 1;
                }
              ;;
            *)
              echo "Invalid action: ${ACTION}. Exiting..."
              exit 1
              ;;
          esac
        shell: /usr/bin/bash -e {0}
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
