name: Run Scripts on Droplet

on:
  workflow_run:
    workflows: ["Terraform Deploy"]  # Trigger this after the Terraform Deploy workflow completes
    types:
      - completed

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Initial Setup Script
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@${{ secrets.DROPLET_PUBLIC_IP }} 'bash /tmp/initial_setup.sh'
        env:
          DROPLET_IP: ${{ secrets.DROPLET_PUBLIC_IP }}

      - name: Run App Setup Script
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@${{ secrets.DROPLET_PUBLIC_IP }} 'bash /tmp/app_setup.sh'
        env:
          DROPLET_IP: ${{ secrets.DROPLET_PUBLIC_IP }}
